### ISSUE TITLE
Make request data available on fetchData handlers

### ISSUE THREAD

**Issue by csarglue** [GlueDigital/universal-scripts#2]
On the server side, we are missing a way of accessing the request data (cookies, headers, ...) when processing a request. This is specially important for fetchData handlers, as these usually need to verify auth or similar tasks that depend on the cookies.
One possible solution would be to put the request data on the store, as it is part of the global state of the application during the request.

**Comment by mancontr** [comment]
I've added a `req` key to the store, with the following format:
```
"req": {
  "headers": {
    "host": "localhost:3000",
    "cookie": "test=value",
    ...
  },
  "ip":"::1"
}
```
It gets deleted before sending it to the client, but is accesible from fetchData methods.
