### ISSUE TITLE
What do you use for async loading data on server side?

### ISSUE THREAD

**Issue by overlookmotel** [GlueDigital/universal-scripts#9]
Hi.

I just noticed that you're using my [react-async-ssr](https://www.npmjs.com/package/react-async-ssr) package for server-side rendering.

If the applications you are building are loading data and rendering it on the server-side, I'd be really interested to know how you got that to work with react-async-ssr.

I just published one solution for this, [react-lazy-data](https://www.npmjs.com/package/react-lazy-data), but I imagine there are other ways to skin this particular cat! Any info you can give would be much appreciated.

**Comment by mancontr** [comment]
Hi,

Thanks for noticing! Yes, we were really looking forward to React supporting suspense on the server-side, and when we found your package, it allowed us to move forward. Thanks for your incredible work!

We are still trying different options on how to use it, but we wanted something very simple. For now, we've created [ruse-fetch](https://www.npmjs.com/package/ruse-fetch), and it has worked well for us so far. As we already have redux integration on universal-scripts, they fit perfectly together, and the state serialization (which was already in place) allows us to send the fetch responses to the client transparently. We just useFetch any URL, and it just works, on both sides.

I don't think we have any public demo using everything together, but I can probably publish one if you're curious. But it's just a matter of creating a universal-scripts project and calling useFetch, as in the example, without any config or adding any provider, as everything is already configured.

If you have any questions or tips, we'd love to hear them!
And again, let me thank you again for your great contribution. It really made a difference for us!

**Comment by overlookmotel** [comment]
Thanks for swift response! Interesting.

I've had a look at [ruse-fetch](https://www.npmjs.com/package/ruse-fetch). The solution of rehydrating via a redux store is nice, however there's one thing I don't understand about how it works on client-side. 

I've raised an issue to ruse-fetch to discuss: https://github.com/GlueDigital/ruse-fetch/issues/2

Totally understand if you don't have time to chat about this, but any info you've gleaned would be really helpful.
